from django.core.management.utils import get_random_secret_key
from rich.console import Console
from json import dumps

def printfc(f, con, string):
    con.print(string, style="dim italic")
    print(string, file=f)

con = Console()
with open("Makefile.secret", "w") as f:
    openrouter_key = input("Enter your OpenRouter API key: ")
    print("Writing to Makefile.secret")
    printfc(f, con, "# This file is automatically generated by")
    printfc(f, con, "# Makefile.secret.generate.py via the Makefile.secret")
    printfc(f, con, "# rule in the Makefile.")
    printfc(f, con, "# ")
    printfc(f, con, "# Do not ever leak this file. If leaked, you will have to")
    printfc(f, con, "# regenerate it as quickly as you can, before the hackers")
    printfc(f, con, "# start bombing your deployment.")
    printfc(f, con, "")
    printfc(f, con, f"export DJANGO_SECRET_KEY={
        dumps(get_random_secret_key()).replace("#", r"\#")
    }")
    printfc(f, con, f"export OPENROUTER_KEY={
        dumps(openrouter_key).replace("#", r"\#")
    }")