[supervisord]
nodaemon=true
user=root

[program:finder]
command=make run SHELL=bash PORT=8080
directory=/app
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
autostart=true
autorestart=true

[program:anubis]
command=/ko-app/anubis
environment=BIND=":80",TARGET="http://127.0.0.1:8080",COOKIE_DYNAMIC_DOMAIN="true",USE_REMOTE_ADDRESS="true"
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
autostart=true
autorestart=true