# Generated by Django 5.2 on 2025-06-20 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('search', '0002_delete_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(max_length=200, unique=True)),
                ('count', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name_plural': 'common searches',
            },
        ),
    ]
