# Generated by Django 5.2 on 2025-04-26 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Indexed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('desc', models.CharField(max_length=255)),
                ('keywds', models.CharField(max_length=255)),
            ],
        ),
    ]
