# Generated by Django 5.2 on 2025-04-26 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexed',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
