# Generated by Django 5.2 on 2025-04-26 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_indexed_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexed',
            name='rank',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='indexed',
            name='keywds',
            field=models.CharField(max_length=65535),
        ),
    ]
