# Generated by Django 5.2 on 2025-04-27 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_indexed_rank_alter_indexed_keywds'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexed',
            name='content',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
