# Generated by Django 5.2 on 2025-04-27 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_indexed_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexed',
            name='content',
            field=models.CharField(max_length=600),
        ),
    ]
