# Generated by Django 5.2 on 2025-05-09 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_indexed_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indexed',
            options={'verbose_name_plural': 'indexed pages'},
        ),
    ]
