# Generated by Django 5.2 on 2025-05-09 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_indexed_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indexed',
            options={'verbose_name_plural': 'pages'},
        ),
    ]
