# Generated by Django 5.2 on 2025-06-22 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_indexed_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indexed',
            options={'verbose_name_plural': 'indexed pages'},
        ),
        migrations.AddField(
            model_name='indexed',
            name='favicon',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='indexed',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='indexed',
            name='keywds',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='indexed',
            name='url',
            field=models.URLField(max_length=255),
        ),
    ]
